# Generated by Django 5.0.4 on 2024-04-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_gapy_number_event_qr_code_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
