# Generated by Django 5.0.4 on 2024-04-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
