# Generated by Django 5.0.4 on 2024-04-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_dislikes_event_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='qr_code',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
