# Generated by Django 5.0.4 on 2024-04-21 15:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGallery', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='banner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='designer',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='img_desinger', to='ArtGallery.designerprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
