# Generated by Django 5.0.4 on 2024-04-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtGallery', '0003_gallery_banner_image_designer_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
