# Generated by Django 5.0.1 on 2024-02-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='sent_to',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='created_by',
            new_name='sender',
        ),
    ]
