# Generated by Django 5.0.4 on 2024-04-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_conversation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
