# Generated by Django 5.0.4 on 2024-04-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_dislikes_project_likes_resume_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
