# Generated by Django 5.0.3 on 2024-04-05 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attach_files',
            field=models.TextField(default=datetime.datetime(2024, 4, 5, 4, 32, 55, 419401, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
