# Generated by Django 5.0.4 on 2024-04-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_attach_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
