# Generated by Django 5.0.4 on 2024-05-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_keyword_post_keyword_userbehavior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=0),
        ),
    ]
