# Generated by Django 5.0.4 on 2024-04-20 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectRecommendations', '0002_alter_project_id'),
        ('account', '0002_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectrecommendations_projects', to='account.user'),
        ),
    ]
