# Generated by Django 5.0.4 on 2024-04-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectRecommendations', '0004_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
