# Generated by Django 5.0.1 on 2024-01-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningresources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='learningresource',
            name='categories',
            field=models.ManyToManyField(related_name='learning_resources', to='learningresources.category'),
        ),
    ]
