# Generated by Django 5.0.4 on 2024-04-20 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_name'),
        ('learningresources', '0002_category_learningresource_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learningresource_comments', to='account.user'),
        ),
    ]
