# Generated by Django 5.0.4 on 2024-04-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningresources', '0003_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='file',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
