# Generated by Django 5.0.3 on 2024-04-15 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_name'),
        ('jobportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
