# Generated by Django 5.0.3 on 2024-04-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_benefit_slug_jobcategory_slug_skill_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
