# Generated by Django 5.0.4 on 2024-04-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_user_points_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
