# Generated by Django 5.0.4 on 2024-04-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_user_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='User_points',
        ),
    ]
