# Generated by Django 5.0.4 on 2024-04-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
