# Generated by Django 5.0.4 on 2024-04-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_customtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='name',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='keyword',
            name='context',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='frequency',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keyword',
            name='relevance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='keyword',
            name='text',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
