# Generated by Django 5.0.4 on 2024-04-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_author_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
