# Generated by Django 5.0.4 on 2024-04-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
