# Generated by Django 5.0.1 on 2024-01-20 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('chat', 'Chat'), ('video_call', 'Video Call')], max_length=50)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MentorComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MentorshipProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.TextField()),
                ('availability', models.CharField(help_text='E.g., Weekdays evenings', max_length=100)),
                ('feedback', models.TextField(blank=True)),
                ('total_stars', models.PositiveIntegerField(default=0)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('accepted_mentees', models.ManyToManyField(blank=True, related_name='accepted_by_mentor', to=settings.AUTH_USER_MODEL)),
                ('comments', models.ManyToManyField(blank=True, related_name='mentorship_profiles', to='MentorshipMatching.mentorcomment')),
                ('contact_methods', models.ManyToManyField(blank=True, related_name='mentorship_profiles', to='MentorshipMatching.contactmethod')),
                ('mentees', models.ManyToManyField(blank=True, related_name='mentored_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mentorcomment',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_mentor', to='MentorshipMatching.mentorshipprofile'),
        ),
        migrations.AddField(
            model_name='contactmethod',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_methods_mentor', to='MentorshipMatching.mentorshipprofile'),
        ),
        migrations.CreateModel(
            name='SharedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_resources_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_resources_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mentorshipprofile',
            name='shared_resources',
            field=models.ManyToManyField(blank=True, related_name='mentorship_profiles', to='MentorshipMatching.sharedresource'),
        ),
    ]
