# Generated by Django 5.0.4 on 2024-04-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorshipMatching', '0003_resourcefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorshipprofile',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mentorshipprofile',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
