# Generated by Django 5.0.4 on 2024-04-20 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_name'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_forum_posts', to='account.user'),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_forum_replies', to='account.user'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
