# Generated by Django 5.0.4 on 2024-04-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_forumpost_author_alter_forumpost_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
