# Generated by Django 5.0.4 on 2024-04-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forumtopic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='likes',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
