# Generated by Django 5.0.4 on 2024-04-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forumpost_dislikes_remove_forumpost_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='image',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
