# Generated by Django 5.0.4 on 2024-04-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingchallenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='challenge',
            field=models.ManyToManyField(blank=True, related_name='codingchallenges', to='codingchallenges.codingchallenge'),
        ),
    ]
