# Generated by Django 5.0.4 on 2024-04-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codingchallenges', '0002_solution_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingchallenge',
            name='language',
        ),
        migrations.AddField(
            model_name='solution',
            name='language',
            field=models.CharField(default='', max_length=50),
        ),
    ]
