# Generated by Django 5.0.1 on 2024-01-20 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollaboratedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('collaborators', models.ManyToManyField(related_name='language_exchange_collaborated_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageExchangeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('availability_times', models.ManyToManyField(blank=True, related_name='language_exchange_profiles', to='LanguageExchange.availabilitytime')),
                ('collaboration_interests', models.ManyToManyField(blank=True, related_name='language_exchange_profiles', to='LanguageExchange.collaborationinterest')),
                ('communication_methods', models.ManyToManyField(blank=True, related_name='language_exchange_profiles', to='LanguageExchange.communicationmethod')),
                ('projects_collaborated', models.ManyToManyField(blank=True, related_name='language_exchange_profiles', to='LanguageExchange.collaboratedproject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageTeaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_languages_as_learner', to='LanguageExchange.languageexchangeprofile')),
                ('teacher_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_languages_as_teacher', to='LanguageExchange.languageexchangeprofile')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LanguageExchange.programminglanguage')),
            ],
            options={
                'unique_together': {('teacher_profile', 'learner_profile', 'language')},
            },
        ),
        migrations.AddField(
            model_name='languageexchangeprofile',
            name='learning_languages',
            field=models.ManyToManyField(related_name='learning_profiles', through='LanguageExchange.LanguageTeaching', to='LanguageExchange.programminglanguage'),
        ),
        migrations.AddField(
            model_name='languageexchangeprofile',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, related_name='language_exchange_profiles', to='LanguageExchange.programminglanguage'),
        ),
        migrations.AddField(
            model_name='languageexchangeprofile',
            name='teaching_languages',
            field=models.ManyToManyField(related_name='teaching_profiles', through='LanguageExchange.LanguageTeaching', to='LanguageExchange.programminglanguage'),
        ),
    ]
