# Generated by Django 5.0.4 on 2024-04-20 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LanguageExchange', '0001_initial'),
        ('account', '0002_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratedproject',
            name='collaborators',
            field=models.ManyToManyField(related_name='language_exchange_collaborated_projects', to='account.user'),
        ),
        migrations.AlterField(
            model_name='languageexchangeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
