# Generated by Django 5.0.4 on 2024-04-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LanguageExchange', '0002_alter_collaboratedproject_collaborators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratedproject',
            name='githublink',
            field=models.TextField(default=''),
        ),
    ]
