# Generated by Django 5.0.4 on 2024-04-22 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LanguageExchange', '0003_collaboratedproject_githublink'),
        ('account', '0006_user_user_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='communicationmethod',
            name='name',
        ),
        migrations.AddField(
            model_name='communicationmethod',
            name='detail',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='communicationmethod',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communicationmethod',
            name='user_profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
        migrations.AddField(
            model_name='communicationmethod',
            name='platform',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='LanguageExchange.communicationplatform'),
        ),
    ]
