# Generated by Django 5.0.4 on 2024-04-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LanguageExchange', '0004_communicationplatform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='languageexchangeprofile',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='languageexchangeprofile',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
