# Generated by Django 5.0.4 on 2024-04-20 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_name'),
        ('codereview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codereview_comments', to='account.user'),
        ),
    ]
